version: '3'

services:
  wishlist:
    build: .
    container_name: wishlist
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      MONGODB_HOST: mongodb
    networks:
      - wishlist-network
    depends_on:
      - mongodb
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: wishlist
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb2024
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    networks:
      - wishlist-network
  mongodb:
    image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: wishlist
      MONGODB_INITDB_ROOT_PASSWORD: mongodb2024
    networks:
      - wishlist-network

networks:
  wishlist-network:
    driver: bridge
