spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_SCHEMA:mychallenge}
      username: ${MONGODB_USERNAME:wishlist}
      password: ${MONGODB_PASSWORD:mongodb2024}
      authentication-database: admin
